version: "3"

services:

  db_bulletin:
    image: postgres:14-alpine
    container_name: db_bulletin_board
    environment:
      PGDATA: /var/lib/postgresql/pgdata
      POSTGRES_DB: bulletin_board
      POSTGRES_PASSWORD: bulletin_password
    volumes:
      - bulletin_postgres_data:/var/lib/postgresql/pgdata
    ports:
      - '5432:5432'
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 5s
      timeout: 5s
      retries: 5

  app_bulletin:
    build: .
    container_name: app_bulletin_board
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    depends_on:
      db_bulletin:
        condition: service_healthy
    volumes:
      - ./.env:/app/.env

volumes:
  bulletin_postgres_data:
