# Generated by Django 4.2.6 on 2023-10-19 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='product description'),
        ),
        migrations.AlterField(
            model_name='review',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_reviews', to='ads.ad', verbose_name='reviewed ad'),
        ),
    ]
