# Generated by Django 4.2.6 on 2023-11-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_ad_description_alter_review_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='preview',
            field=models.ImageField(blank=True, upload_to='ads_preview', verbose_name='ad_preview'),
        ),
    ]
